In [2]:
#How to declare numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#How to declare 2d array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(type(arr2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([1,2,3,4,5])
# slicing of single-dimentional array
print(arr[0])   # it prints first element
print(arr[-1])   # it prints last element
print(arr[0:])  # it prints 0 to last index
print(arr[:])   # it prints all the items
print(arr[:5])   # it prints first element to 5th

1
5
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [17]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
# slicing of 2d array
print(arr2[0,0:3])   # it prints 0 to 2 index of sub-array of 0th index of main array
print(arr2[0:2])     # it prints 0 to 1st index of main array
print(arr2[0:2,0:2])   # it prints 0th to 1st index of first two sub array
print(arr2[0:2,0:3])   # it prints 0th to 2nd index of both sub array, we can not print different indexes
print(arr2[0,0:])
print(arr2[1,0:2])

[1 2 3]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2]
 [6 7]]
[[1 2 3]
 [6 7 8]]
[1 2 3 4 5]
[6 7]
